sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - sed -i s/GITALK_CLIENT_ID/$CLIENT_ID/ themes/diaspora/_config.yml
  - sed -i s/GITALK_CLIENT_SECRET/$CLIENT_SECRET/ themes/diaspora/_config.yml
  - hexo generate # generate static files
  - echo "blog.zouyapeng.com" > public/CNAME
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
