# 头部菜单，title: link
menu:
  首页: /
#  分类: /categories
  标签: /tags
  归档: /archives
  关于: /about

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐（随机播放）
mp3:
    - https://cdn.jsdelivr.net/gh/bob-zou/bob-zou.github.io/source/music/BeethovenVirus.mp3
    - https://cdn.jsdelivr.net/gh/bob-zou/bob-zou.github.io/source/music/Lemon.mp3
    - https://cdn.jsdelivr.net/gh/bob-zou/bob-zou.github.io/source/music/MerryChristmas.mp3
    - https://cdn.jsdelivr.net/gh/bob-zou/bob-zou.github.io/source/music/PurplePassion.mp3
    - https://cdn.jsdelivr.net/gh/bob-zou/bob-zou.github.io/source/music/光年之外.mp3
    - https://cdn.jsdelivr.net/gh/bob-zou/bob-zou.github.io/source/music/山楂树の恋.mp3
    - https://cdn.jsdelivr.net/gh/bob-zou/bob-zou.github.io/source/music/岁月神偷.mp3

# 首页封面图, 为空时取文章的cover作为封面(注意跨域问题,建议使用同源图片)
welcome_cover: https://cdn.jsdelivr.net/gh/bob-zou/bob-zou.github.io/themes/diaspora/source/img/welcome.png

# 默认文章封面图（随机调用,支持外链）
cover:
  - https://cdn.jsdelivr.net/gh/bob-zou/bob-zou.github.io/themes/diaspora/source/img/cover.jpg
  - https://cdn.jsdelivr.net/gh/bob-zou/bob-zou.github.io/themes/diaspora/source/img/welcome.png

# 是否使用mathjax
mathjax: false


# 是否关闭默认滚动条
scrollbar: true

# 本地搜索,请将索引文件放在网站根目录,或修改主题js文件的path值
local_search:
    # 是否启用
    enable: true

# 是否显示 一言(hitokoto)
hitokoto: true

# 链接(可选:facebook,twitter,github,wechat,email)
links:
#    facebook: /
#    twitter: /
    github: https://github.com/bob-zou
    wechat: https://cdn.jsdelivr.net/gh/bob-zou/bob-zou.github.io/themes/diaspora/source/img/logo.png
    email: mailto:zyp19901009@gmail.com

# 备案
beian:
    # 是否显示备案信息
    enable: true
    # 是否在主页面最底下显示备案信息(虽然丑，但是完全满足规定要求)
    enableFooter: false
    # 备案号
    beianInfo: 苏ICP备16016567号-1
    # 链接地址
    link: https://cdn.jsdelivr.net/gh/bob-zou/bob-zou.github.io/themes/diaspora/source/img/beian.png

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否启用评论功能
    enable: true
    # 是否自动展开评论框
    autoExpand: true
    # 应用编号
    clientID: 'GITALK_CLIENT_ID'
    # 应用秘钥
    clientSecret: 'GITALK_CLIENT_SECRET'
    # issue仓库名
    repo: 'bob-zou.github.io'
    # Github名
    owner: 'bob-zou'
    # Github名
    admin: ['bob-zou']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: BobZou

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: G-MTN9237PJK

# 网站ico
favicon: https://cdn.jsdelivr.net/gh/bob-zou/bob-zou.github.io/themes/diaspora/source/img/favicon.png

# rss文件
rss: atom.xml
